mariamCurculumVitae/src/Entity/Mariam.php
<?php

namespace App\Entity;

use App\Repository\MariamRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MariamRepository::class)
 */
class Mariam
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $accroche;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ecole;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $mobile;

    /**
     * @ORM\Column(type="text")
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="mariams")
     */
    private $utilisateur;

    
    
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAccroche(): ?string
    {
        return $this->accroche;
    }

    public function setAccroche(string $accroche): self
    {
        $this->accroche = $accroche;

        return $this;
    }

    public function getEcole(): ?string
    {
        return $this->ecole;
    }

    public function setEcole(string $ecole): self
    {
        $this->ecole = $ecole;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(string $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMobile(): ?int
    {
        return $this->mobile;
    }

    public function setMobile(int $mobile): self
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

   

   

   
}

mariamCurculumVitae/src/Form/MariamType.php
<?php

namespace App\Form;

use App\Entity\Mariam;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MariamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom')
            ->add('nom')
            ->add('titre')
            ->add('accroche')
            ->add('ecole')
            ->add('entreprise')
            ->add('email')
            ->add('mobile')
            ->add('image')
            ->add('ville')
            ->add('code_postal')
            ->add('pays')
            ->add('utilisateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Mariam::class,
        ]);
    }
}

mariamCurculumVitae/src/Controller/MariamController.php
<?php

namespace App\Controller;

use App\Entity\Mariam;
use App\Form\MariamType;
use App\Repository\MariamRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/mariam")
 */
class MariamController extends AbstractController
{
    /**
     * @Route("/", name="app_mariam_index", methods={"GET"})
     */
    public function index(MariamRepository $mariamRepository): Response
    {
        return $this->render('mariam/index.html.twig', [
            'mariams' => $mariamRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_mariam_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MariamRepository $mariamRepository): Response
    {
        $mariam = new Mariam();
        $form = $this->createForm(MariamType::class, $mariam);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mariamRepository->add($mariam, true);

            // $mariam->setVerifier(false);

            return $this->redirectToRoute('app_mariam_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mariam/new.html.twig', [
            'mariam' => $mariam,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_mariam_show", methods={"GET"})
     */
    public function show(Mariam $mariam): Response
    {
        return $this->render('mariam/show.html.twig', [
            'mariam' => $mariam,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_mariam_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Mariam $mariam, MariamRepository $mariamRepository): Response
    {
        $form = $this->createForm(MariamType::class, $mariam);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mariamRepository->add($mariam, true);

            return $this->redirectToRoute('app_mariam_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mariam/edit.html.twig', [
            'mariam' => $mariam,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_mariam_delete", methods={"POST"})
     */
    public function delete(Request $request, Mariam $mariam, MariamRepository $mariamRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mariam->getId(), $request->request->get('_token'))) {
            $mariamRepository->remove($mariam, true);
        }

        return $this->redirectToRoute('app_mariam_index', [], Response::HTTP_SEE_OTHER);
    }
}

mariamCurculumVitae/templates/mariam/_delete_form.html.twig
<form method="post" action="{{ path('app_mariam_delete', {'id': mariam.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mariam.id) }}">
    <button class="btn">Delete</button>
</form>

mariamCurculumVitae/templates/mariam/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mariam{% endblock %}

{% block body %}
    <h1>Edit Mariam</h1>

    {{ include('mariam/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mariam_index') }}">back to list</a>

    {{ include('mariam/_delete_form.html.twig') }}
{% endblock %}

mariamCurculumVitae/templates/mariam/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mariam index{% endblock %}

{% block body %}
    <h1>Mariam index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th>Titre</th>
                <th>Accroche</th>
                <th>Ecole</th>
                <th>Entreprise</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Image</th>
                <th>Ville</th>
                <th>Code_postal</th>
                <th>Pays</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mariam in mariams %}
            <tr>
                <td>{{ mariam.id }}</td>
                <td>{{ mariam.prenom }}</td>
                <td>{{ mariam.nom }}</td>
                <td>{{ mariam.titre }}</td>
                <td>{{ mariam.accroche }}</td>
                <td>{{ mariam.ecole }}</td>
                <td>{{ mariam.entreprise }}</td>
                <td>{{ mariam.email }}</td>
                <td>{{ mariam.mobile }}</td>
                <td>{{ mariam.image }}</td>
                <td>{{ mariam.ville }}</td>
                <td>{{ mariam.codePostal }}</td>
                <td>{{ mariam.pays }}</td>
                <td>
                    <a href="{{ path('app_mariam_show', {'id': mariam.id}) }}">show</a>
                    <a href="{{ path('app_mariam_edit', {'id': mariam.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_mariam_new') }}">Create new</a>
{% endblock %}

mariamCurculumVitae/templates/mariam/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mariam{% endblock %}

{% block body %}
    <h1>Create new Mariam</h1>

    {{ include('mariam/_form.html.twig') }}

    <a href="{{ path('app_mariam_index') }}">back to list</a>
{% endblock %}

mariamCurculumVitae/templates/mariam/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mariam{% endblock %}

{% block body %}
    <h1>Mariam</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mariam.id }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ mariam.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ mariam.nom }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ mariam.titre }}</td>
            </tr>
            <tr>
                <th>Accroche</th>
                <td>{{ mariam.accroche }}</td>
            </tr>
            <tr>
                <th>Ecole</th>
                <td>{{ mariam.ecole }}</td>
            </tr>
            <tr>
                <th>Entreprise</th>
                <td>{{ mariam.entreprise }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ mariam.email }}</td>
            </tr>
            <tr>
                <th>Mobile</th>
                <td>{{ mariam.mobile }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ mariam.image }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ mariam.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ mariam.codePostal }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ mariam.pays }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_mariam_index') }}">back to list</a>

    <a href="{{ path('app_mariam_edit', {'id': mariam.id}) }}">edit</a>

    {{ include('mariam/_delete_form.html.twig') }}
{% endblock %}