mariamCurculumVitae/src/Entity/Experiences.php
<?php

namespace App\Entity;

use App\Repository\ExperiencesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExperiencesRepository::class)
 */
class Experiences
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $sous_titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="experiences")
     */
    private $utilisateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSousTitre(): ?string
    {
        return $this->sous_titre;
    }

    public function setSousTitre(string $sous_titre): self
    {
        $this->sous_titre = $sous_titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }
}

mariamCurculumVitae/src/Form/ExperiencesType.php
<?php

namespace App\Form;

use App\Entity\Experiences;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExperiencesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('sous_titre')
            ->add('description')
            ->add('date_debut')
            ->add('date_fin')
            ->add('utilisateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Experiences::class,
        ]);
    }
}

mariamCurculumVitae/src/Controller/ExperiencesController.php
<?php

namespace App\Controller;

use App\Entity\Experiences;
use App\Form\ExperiencesType;
use App\Repository\ExperiencesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/experiences")
 */
class ExperiencesController extends AbstractController
{
    /**
     * @Route("/", name="app_experiences_index", methods={"GET"})
     */
    public function index(ExperiencesRepository $experiencesRepository): Response
    {
        return $this->render('experiences/index.html.twig', [
            'experiences' => $experiencesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_experiences_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ExperiencesRepository $experiencesRepository): Response
    {
        $experience = new Experiences();
        $form = $this->createForm(ExperiencesType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $experiencesRepository->add($experience, true);

            return $this->redirectToRoute('app_experiences_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('experiences/new.html.twig', [
            'experience' => $experience,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_experiences_show", methods={"GET"})
     */
    public function show(Experiences $experience): Response
    {
        return $this->render('experiences/show.html.twig', [
            'experience' => $experience,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_experiences_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Experiences $experience, ExperiencesRepository $experiencesRepository): Response
    {
        $form = $this->createForm(ExperiencesType::class, $experience);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $experiencesRepository->add($experience, true);

            return $this->redirectToRoute('app_experiences_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('experiences/edit.html.twig', [
            'experience' => $experience,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_experiences_delete", methods={"POST"})
     */
    public function delete(Request $request, Experiences $experience, ExperiencesRepository $experiencesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$experience->getId(), $request->request->get('_token'))) {
            $experiencesRepository->remove($experience, true);
        }

        return $this->redirectToRoute('app_experiences_index', [], Response::HTTP_SEE_OTHER);
    }
}

mariamCurculumVitae/templates/experiences/_delete_form.html.twig
<form method="post" action="{{ path('app_experiences_delete', {'id': experience.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ experience.id) }}">
    <button class="btn">Delete</button>
</form>

mariamCurculumVitae/templates/experiences/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Experiences{% endblock %}

{% block body %}
    <h1>Edit Experiences</h1>

    {{ include('experiences/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_experiences_index') }}">back to list</a>

    {{ include('experiences/_delete_form.html.twig') }}
{% endblock %}

mariamCurculumVitae/templates/experiences/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Experiences index{% endblock %}

{% block body %}
    <h1>Experiences index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Sous_titre</th>
                <th>Description</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for experience in experiences %}
            <tr>
                <td>{{ experience.id }}</td>
                <td>{{ experience.titre }}</td>
                <td>{{ experience.sousTitre }}</td>
                <td>{{ experience.description }}</td>
                <td>{{ experience.dateDebut ? experience.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ experience.dateFin ? experience.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_experiences_show', {'id': experience.id}) }}">show</a>
                    <a href="{{ path('app_experiences_edit', {'id': experience.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<div class="text-center mb-5">
			<a class="btn btn-primary mt-5" href="{{ path('app_poste_index') }}">
								Retour</a>
		</div>
    <a href="{{ path('app_experiences_new') }}">Create new</a>
{% endblock %}

mariamCurculumVitae/templates/experiences/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Experiences{% endblock %}

{% block body %}
    <h1>Create new Experiences</h1>

    {{ include('experiences/_form.html.twig') }}

    <a href="{{ path('app_experiences_index') }}">back to list</a>
{% endblock %}

mariamCurculumVitae/templates/experiences/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Experiences{% endblock %}

{% block body %}
    <h1>Experiences</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ experience.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ experience.titre }}</td>
            </tr>
            <tr>
                <th>Sous_titre</th>
                <td>{{ experience.sousTitre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ experience.description }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ experience.dateDebut ? experience.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ experience.dateFin ? experience.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_experiences_index') }}">back to list</a>

    <a href="{{ path('app_experiences_edit', {'id': experience.id}) }}">edit</a>

    {{ include('experiences/_delete_form.html.twig') }}
{% endblock %}